# Generated by Django 4.2.3 on 2023-07-09 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0002_medicine"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicine",
            name="disease",
            field=models.CharField(
                choices=[
                    ("Cough", "Cough"),
                    ("Fever", "Fever"),
                    ("SkinCare", "Skin Care"),
                    ("FitnessandWellness", "Fitness and Wellness"),
                    ("BabyCare", "Baby Care"),
                    ("Diabetis", "Diabetis"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.medicine"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
