# Generated by Django 4.2.3 on 2024-07-25 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_payment_orderplaced"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="user",
        ),
        migrations.DeleteModel(
            name="OrderPlaced",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
